### ISSUE TITLE
Dificuldades

### ISSUE THREAD

**Issue by bernaferrari** [danilofrp/consolidador-cei#1]
Tive os seguintes problemas ao executar:

- precisei remover o `decimal = ','` no `pd.read_excel`, se não `TypeError: read_excel() got an unexpected keyword argument 'decimal'`.
- precisei adicionar: `if (cei_file == '.DS_Store'): continue` para evitar o arquivo do Mac dando erro.
- tive uns warnings: WARNING *** file size (21239) not 512 + multiple of sector size (512)
- em valor total você poderia colocar negativo quando venda.

Mas no geral tudo certo, ótima ideia.

**Comment by danilofrp** [comment]
Bernardo, obrigado pelos comentários!

Quanto ao parâmetro "decimal", o meu funciona com ou sem ele, e lembro de precisar dele quando desenvolvi. Possivelmente uma atualização no pandas removeu essa necessidade, então removi o parâmetro também. Adicionei o mesmo tratamento que você para compatibilidade com Mac, e também reformulei a forma como os arquivos são lidos para que o warning de tamanho não apareça mais (me parece ser algo de como o CEI monta os arquivos.)

Também implementei a sua sugestão, valor total e quantidade agora aparecem negativos no arquivo consolidado quando a operação é de venda.

Fico feliz que tenha gostado, espero que facilite a vida
